name: Android CI with macOS

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Appium
        run: |
          npm install -g appium@next
          appium driver install uiautomator2
        
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          target: google_apis
          arch: x86_64
          profile: pixel_xl
          cores: 2
          ram-size: 5120M 
          sdcard-path-or-size: 2000M
          avd-name: Pixel
          force-avd-creation: false
          emulator-options: -no-window -gpu guest -noaudio -no-boot-anim -camera-back none -accel on
          disable-animations: true
          script: mvn test -PRegression -f ./tests/pom.xml -q

      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: functional-test-report
          path: tests/reports
