name: Android

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29
      
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Install Appium
        run: |
          npm install -g appium@next
          appium driver install uiautomator2

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: pixel_xl
          avd-name: Pixel
          force-avd-creation: false
          emulator-options: -no-window
          disable-animations: false
          script: mvn test -PRegression -f ./tests/pom.xml -q

      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: result
          path: tests/myImage.jpg
